### ISSUE TITLE
Bad request-no token provided in body

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [vastus/express-hcaptcha#4]
I'm working on adding a captcha for my assignment, but every time I complete the captcha, it gives the same error: "bad request - no token provided in body". How do I fix this?

[code](https://replit.com/@RahulChoubey1/Dance-Assignment#index.js)

**Comment by tkundrat** [comment]
Hi, can you share how you fixed the issue? I am having the same error...

**Comment by a-a-GiTHuB-a-a** [comment]
I just sent a request directly to hCaptcha's site using `axios`.

**Comment by cheslin23** [comment]
should now be working
