### ISSUE TITLE
req.body.token does not exist

### ISSUE THREAD

**Issue by eperezcosano** [vastus/express-hcaptcha#7]
**req.body.token** does not exist. It should be replaced with **req.body['h-captcha-response']** which is the POST parameter returned form the server.

**Comment by AnasQiblawi** [comment]
- I use this
```js
const token = req.body["g-recaptcha-response"] ?? req.body["h-captcha-response"] ?? req.query["g-recaptcha-response"] ?? req.query["h-captcha-response"];
```

**Comment by cheslin23** [comment]
`app.use(bodyParser.json()); // required by express-hcaptcha`
